services:
  - type: web
    name: not-sistemi
    env: python
    buildCommand: ""
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: your_database_url_here
      - key: PORT
        value: 10000
